Status report button sizes adjusted
Gerfatz/m150-byod-launcher pull request #7
Opened 2021-01-14 19:23 UTC by PersonCopy

The Successnd Error buttons in AttendSession.vue have been set to "large"

2021-01-14 19:46 UTC, Gerfatz requested changes
appsettings.Development.json is .gitignore ine neh

2021-01-14 19:46 UTC, Gerfatz commented on appsettings.Development.json
> -    "MariaDb": "Server=localhost;Database=byodlauncher;Port=13306;User=user;Password=password;"
Das File au no is git ignore ine. Denn git rm --cached <Filepath> usfüre zum es usem Repo remove

2021-01-15 12:50 UTC, Gerfatz approved these changes

2021-01-15 13:44 UTC, Adrian37x approved these changes

2021-01-15 14:22 UTC, merged